// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyilQQlcWESgYyhW5kSTrmd5Oru0jZfaE',
    appId: '1:475937151394:web:084d53a3647c88a5d43afb',
    messagingSenderId: '475937151394',
    projectId: 'foodapp-437e9',
    authDomain: 'foodapp-437e9.firebaseapp.com',
    databaseURL: 'https://foodapp-437e9-default-rtdb.firebaseio.com',
    storageBucket: 'foodapp-437e9.firebasestorage.app',
    measurementId: 'G-GQ9SVMM6N2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQo-OwXN9YMaYX7hmpnCpxaR1zDXp-mxg',
    appId: '1:475937151394:android:267db5731a5147c0d43afb',
    messagingSenderId: '475937151394',
    projectId: 'foodapp-437e9',
    databaseURL: 'https://foodapp-437e9-default-rtdb.firebaseio.com',
    storageBucket: 'foodapp-437e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUDsqyC31857Fzto7wR0--CTsvn0gyKFk',
    appId: '1:475937151394:ios:e186b06eda0d5138d43afb',
    messagingSenderId: '475937151394',
    projectId: 'foodapp-437e9',
    databaseURL: 'https://foodapp-437e9-default-rtdb.firebaseio.com',
    storageBucket: 'foodapp-437e9.firebasestorage.app',
    iosBundleId: 'com.example.visitifyflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUDsqyC31857Fzto7wR0--CTsvn0gyKFk',
    appId: '1:475937151394:ios:e186b06eda0d5138d43afb',
    messagingSenderId: '475937151394',
    projectId: 'foodapp-437e9',
    databaseURL: 'https://foodapp-437e9-default-rtdb.firebaseio.com',
    storageBucket: 'foodapp-437e9.firebasestorage.app',
    iosBundleId: 'com.example.visitifyflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyilQQlcWESgYyhW5kSTrmd5Oru0jZfaE',
    appId: '1:475937151394:web:b44061568d69ae7cd43afb',
    messagingSenderId: '475937151394',
    projectId: 'foodapp-437e9',
    authDomain: 'foodapp-437e9.firebaseapp.com',
    databaseURL: 'https://foodapp-437e9-default-rtdb.firebaseio.com',
    storageBucket: 'foodapp-437e9.firebasestorage.app',
    measurementId: 'G-Q1HB7C55NE',
  );
}
